### ISSUE TITLE
Some awesome AT blog posts

### ISSUE THREAD

**Issue by blundell** [amitshekhariitbhu/awesome-android-things#9]
https://www.novoda.com/blog/writing-your-first-android-things-driver-p1/
http://blog.blundellapps.co.uk/testing-android-things-iot-meets-java/
https://riggaroo.co.za/android-things-hardware-basics/

**Comment by friedger** [comment]
Fixed by https://github.com/amitshekhariitbhu/awesome-android-things/commit/34a2edbf36a1f5b7762bd7abb36838ea03f99572

@blundell Feel free to send pull requests directly :-)
